# Path to your oh-my-zsh installation.
export ZSH=/Users/pauloancheta/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git kubectl docker)

# User configuration

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='nvim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
####################################
#        CONFIG CHANGE!            #
####################################

#---------CONFIG ALIAS--------------
alias zshconfig="nvim ~/.zshrc"
alias ohmyzsh="nvim ~/.oh-my-zsh"
alias gitconfig="nvim ~/.gitconfig"
alias vimconfig="nvim ~/.vimrc.after"
alias nvimconfig="nvim ~/.config/nvim/init.vim"

#---------BETTER TERMINAL-----------
alias ll='ls -lA'       # preferred ls configuration
alias ..='cd ../'    # prefereed cd configuration
alias ...='cd ../../' # preferred cd configuration

# VIM
alias vim='nvim'

# HEROKU
alias gph='git push heroku master' # push master branch to heroku

# RUBY / RAILS
alias rs='rails s'
alias rc='rails c'
alias cc='cucumber'
alias be='bundle exec'
alias watch='watch '
alias east='aws-ec2-list --columns="project, stack_name, public_dns_name, instance_id, state"'
alias west='aws-ec2-list --region=us-west-2 --columns="project, stack_name, instance_id, public_dns_name, state"'

# ELIXIR / PHOENIX
alias mps='mix phoneix.server'
alias mdg='mix deps.get'

# DOCKER
alias dr='docker'
alias dri='docker images'
alias drb='docker build . -t'
alias drc='docker-compose'
alias drcup='docker-compose up -d'
alias dr_ps_clear='docker ps -f "status=exited" -q | xargs docker rm'
alias dr_img_clear='docker images -f "dangling=true" -q | xargs docker rmi'

alias k='kubectl'
alias ku='kubectl --kubeconfig kubeconfig'
alias kun='kubectl --kubeconfig kubeconfig -n unbounce-system'
alias kinfo='watch "kubectl get deployment,svc,pods,pvc"'

####################################
#        PATH CHANGE!              #
####################################
# for elixir manager
[[ -s "$HOME/.kiex/scripts/kiex" ]] && source "$HOME/.kiex/scripts/kiex"

# for go lang
export GOPATH=~/go
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$GOPATH/bin

# python ML
export MPLBACKEND="module://itermplot"
export ITERMPLOT=rv
# use pyenv
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init -)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # load nvm

export MANPATH=/usr/local/man:$MANPATH
# export PATH=/usr/local/heroku/bin:$PATH
export PATH="$HOME/.dotfiles/scripts:$PATH"

# for java
# export JAVA_HOME=$(/usr/libexec/java_home)

# mysql 5.6
# export PATH="/usr/local/opt/mysql@5.6/bin:$PATH"

# rbenv paths
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
export PATH="./bin:$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"

####################################
#      CURRENT PROJECTS            #
####################################
alias dotfiles='cd ~/.dotfiles'
alias grimoire='vim ~/grimoire'

# added by travis gem
[ -f /Users/pauloancheta/.travis/travis.sh ] && source /Users/pauloancheta/.travis/travis.sh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/pauloancheta/go/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/pauloancheta/go/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/pauloancheta/go/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/pauloancheta/go/google-cloud-sdk/completion.zsh.inc'; fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

